// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWind():Promise<void>;

export function GetWindPosition():Promise<main.Position>;

export function MaxWind():Promise<void>;

export function MinWind():Promise<void>;

export function SetWinPosition(arg1:main.Position):Promise<void>;

export function UnMaxWind():Promise<void>;
