// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWind():void;

export function MaxWind():void;

export function MinWind():void;

export function UnMaxWind():void;
