// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWind():Promise<void>;

export function MaxWind():Promise<void>;

export function MinWind():Promise<void>;

export function UnMaxWind():Promise<void>;
